name: Analyse statique avec Semgrep

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/semgrep_analyse.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep_scan:
    name: Exécuter Semgrep sur le code Python
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation de Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Exécution de l’analyse Semgrep
        run: |
          # Génération du rapport JSON principal
          semgrep --config=auto --error --json > rapport_semgrep.json || true

          # Génération du rapport texte (résumé)
          semgrep --config=auto --error --text > rapport_semgrep.txt || true

          # Génération du rapport HTML depuis le JSON
          semgrep --config=auto --error --json | semgrep report --json-input --html --output rapport_semgrep.html || true

      - name: Sauvegarde des rapports Semgrep
        uses: actions/upload-artifact@v4
        with:
          name: rapport-semgrep
          path: |
            rapport_semgrep.json
            rapport_semgrep.html
            rapport_semgrep.txt
